### ISSUE TITLE
Search filter

### ISSUE THREAD

**Issue by matuskrizo** [Wradgio/StretchShop#11]
When I search for product Ferdo Mravec by keyword "ferdo", nothing was found.

**Comment by Wradgio** [comment]
In a MongoDB, if a search is case-sensitive depends on if and how is that field indexed. This issue is therefore not related to StretchShop, but to a data source it uses. Links for more information about the problem:

1. https://stackoverflow.com/questions/1863399/mongodb-is-it-possible-to-make-a-case-insensitive-query#answer-40914924
2. https://docs.mongodb.com/manual/core/index-case-insensitive/
3. https://docs.mongodb.com/manual/reference/collation/
