### ISSUE TITLE
Improvements - Logged in - profile dashboard - delete my profile (GDPR)

### ISSUE THREAD

**Issue by matuskrizo** [Wradgio/StretchShop#15]
**Logged in - profile dashboard**
I am missing:
- delete my profile (GDPR)
- tab with info about my orders

**after add to cart animations**
personaly I don´t like this animation :) I think that some better UX methods exist  :)

**products page**
I think, that is better show all products there (or categories boxes). Empty page is not good.

**product detail**
- open product image in modal
- missing product details example like siye, color, etc

https://demo.storefrontcloud.io/women/tops-women/tees-women/tees-25/elisa-evercool-and-trade-tee-1465.html?childSku=WS06

**Comment by Wradgio** [comment]
### Feedback

1. Logged in - profile dashboard
    1. delete my profile - Good point :)
    2. tab with info about my orders - it's here - ![Login - StretchShop](https://user-images.githubusercontent.com/1776976/72282141-575ef500-363c-11ea-8641-e7f709c50002.png)
2. after add to cart animations - I agree it's not the most fancy one, can add it to the [ToDo list with design-related topics](https://github.com/Wradgio/StretchShop/wiki/ToDo-lists#design).
3. products page - Sure, but every e-shop would like to have something else there, that's why I am preparing something more flexible, see issue #7 - calling functions from pages. It should be part of v0.4 release.
4. product detail
    1. open product image in modal - good one - adding to [design todo's](https://github.com/Wradgio/StretchShop/wiki/ToDo-lists#design).
    2. missing product details example like size, color, etc - adding to [design todo's](https://github.com/Wradgio/StretchShop/wiki/ToDo-lists#design).

Thank you for your time and finding out these points.

###  Summary

I am about to continue this issue with this point:
**1.1 - Logged in - profile dashboard - delete my profile (GDPR)**

Also, added 3 items into the design ToDo list.

**Comment by Wradgio** [comment]
Added in v0.3.10, closing.
